### ISSUE TITLE
`dbt_tmp` tables not dropped for Python models

### ISSUE THREAD

**Issue by geo-martino** [databricks/dbt-databricks#1010]
### Describe the bug
When running Python models, temporary tables with the `dbt_tmp` suffix are created as part of the replace flow. The temporary tables should be dropped after adding their data to the main table but I'm finding these tables are left behind causing a massive build up of these tables in our catalog. I don't see this behaviour for SQL models at all.

I haven't had much time to look at some edge cases and see if any certain config is affecting this (e.g. using `unique_tmp_table_suffix`) but I should have time to investigate further next week if needed.

### Steps To Reproduce
I have the following relevant config set in my project file:
```yaml
flags:
  use_materialization_v2: yes
  use_user_folder_for_python: yes

models:
  +unique_tmp_table_suffix: yes  # needed to run updates to tables concurrently
  +view_update_via_alter: yes
```

This bug should happen upon generating any python model for a relation which needs to be replaced.

### Expected behavior
The temporary tables should be dropped after adding their data to the main table

### Screenshots and log output
<img width="288" alt="Image" src="https://github.com/user-attachments/assets/534a3ab2-b86f-40a5-a351-1fdcece1a2e9" />

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.9.4
  - latest:    1.9.4 - Up to date!

Plugins:
  - databricks: 1.10.1 - Up to date!
  - spark:      1.9.2  - Up to date!
```

**The operating system you're using:**
MacOS 15.4.1

**The output of `python --version`:**
Python 3.12.10

### Additional context
We are executing the dbt command from an all-purpose cluster which also handles the execution of of the Python models too.
