### ISSUE TITLE
ACL permissions not applied to notebook jobs created by DBT Python model

### ISSUE THREAD

**Issue by case-k-git** [databricks/dbt-databricks#1014]
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?

ACL permissions not applied to notebook jobs created by DBT Python model

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

1. Create configs

config.yaml
```
version: 2
models:
- name: test
  config:
    materialized: table
    python_job_config:
      grants:
        view: [{"group_name": "<group_name>"}]
    database:<catalgo_name>
    schema:<schema_name>
    submission_method: all_purpose_cluster
    create_notebook: True
    cluster_id: "<cluster_id>"
```
2. Create sample DBT Python model
```

def model(dbt, session):
    dbt.config(
        materialized='table',
        tags=['test'],
    )
    return session.sql("SELECT current_timestamp() AS createdtime")
```

3. Execute python model with debug option
```
 dbt run  --target=nonprod --select tag:test --debug
```
We can confirm access_control_list is passed. But there is no permission into created Notebook jobs enven if granted from python_job_config.
```
'access_control_list': [{'service_principal_name': '<service_principal_name>', 'permission_level': 'IS_OWNER'}, {'group_name': '<group_name>', 'permission_level': 'CAN_VIEW'}], 'queue': {'enabled': True}} and additional_job_settings={additional_job_settings}
```
### Expected behavior

Grant the permission which is defined by  python_job_config
```
grants:
    view: [{"group_name": "<group_name>"}]
```

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.9.4
  - latest:    1.9.4 - Up to date!

Plugins:
  - databricks: 1.10.1 - Up to date!
  - spark:      1.9.2  - Up to date!
```

**The operating system you're using:**

**The output of `python --version`:**

### Additional context

I am working on to fix this issue.
