### ISSUE TITLE
Oauth U2M Azure regression/breaking change in 1.10

### ISSUE THREAD

**Issue by troyel** [databricks/dbt-databricks#1016]
### Describe the bug
After upgrading from dbt-databricks 1.9.7 to 1.10.1 the Oauth configuration for Azure that is set up following [this guide](https://learn.microsoft.com/en-us/azure/databricks/integrations/configure-oauth-dbt#configure-user-to-machine-u2m-authentication-for-dbt-core) no longer seem to work with Databricks returning with the error:
{"error_description":"OAuth application with client_id: '(...)' not available in Databricks account '(...)'.","error":"invalid_request"} and the dbt debug action stuck without throwing an error (need to force quit in vscode).

### Steps To Reproduce
Set up Azure U2M app registration with redirect url to localhost:8020 as documented [here](https://learn.microsoft.com/en-us/azure/databricks/integrations/configure-oauth-dbt#configure-user-to-machine-u2m-authentication-for-dbt-core)

Connect using dbt core with a profile similar to the below:

```
dbt profile:
databricks_dbt:
  outputs:
    dev:
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_PATH') }}"
      schema: "{{ env_var('SCHEMA') }}"
      threads: 4
      token: ""
      type: databricks
      auth_type: oauth
      client_id: "(...)"
```

### Expected behavior
I expect to be authenticated and be able to work as usual.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.9.4
  - latest:    1.9.4 - Up to date!

Plugins:
  - databricks: 1.10.1 - Up to date!
  - spark:      1.9.2  - Up to date!
```

**The operating system you're using:**
Windows 11
**The output of `python --version`:** 
Python 3.12.8

### Additional context
I am wondering if this issue has something to do with this comment from the [PR bumping the python SDK ](https://github.com/databricks/dbt-databricks/pull/827)version to 0.36.0

> With this change one thing that will no longer work is if customer are using non-databricks OAuth client for U2M case it will not work, since the python sdk does not support modify [redirectUrl](https://github.com/databricks/databricks-sdk-py/blob/ee6e70a1e3a38b465405d41f39f4447ad7dd3090/databricks/sdk/credentials_provider.py#L204C5-L204C17)/[scopes](https://github.com/databricks/databricks-sdk-py/blob/main/databricks/sdk/oauth.py#L467).
@eric-wang-1990 

If the implications are that Azure OAuth as set up using Microsoft documentation is no longer working this is a big breaking change and should potentially be exclamated and followed by some migration guidance to a working Oauth set up.
