### ISSUE TITLE
1.10.2 fails with [SCALAR_SUBQUERY_TOO_MANY_ROWS] with two or more foreign_keys defined

### ISSUE THREAD

**Issue by thomascupertino** [databricks/dbt-databricks#1034]
### Describe the bug
Running dbt build or run with dbt-databricks 1.10.2 fails if two or more foreign_key constraints are defined in the YAML for the same model. It raises:

`[SCALAR_SUBQUERY_TOO_MANY_ROWS] More than one row returned by a subquery used as an expression.
SQLSTATE: 21000`
### Steps To Reproduce
1. Use dbt-databricks 1.10.2

2. Add models

3. Add multiple FKs in the same model e.g:

Model 1:  
```yaml
  name: entity_a
  constraints:
    - type: primary_key
      columns: ["entity_a_id"]
      name: pk_entity_a
```      
 
Model 2:  
```yaml
  name: entity_b
  constraints:
    - type: primary_key
      columns: [entity_b_id]
      name: pk_entity_b
```      
 
Model 3:
```yaml
  name: entity_c
  constraints:
    - type: primary_key
      columns: ["entity_c_id"]
      name: pk_entity_c
 
    - type: foreign_key
      columns: ["entity_a_id"]
      name: fk_beta_to_entity_a
      to: ref('entity_a')
      to_columns: ["entity_a_id"]
   
    - type: foreign_key
      columns: ["entity_b_id"]
      name: fk_beta_to_entity_b
      to: ref('entity_b')
      to_columns: ["entity_b_id"]
```

### Expected behavior
- dbt build/run completes successfully.
- For every model that declares more than one foreign_key constraint, dbt generates and executes all corresponding ALTER TABLE … ADD CONSTRAINT statements without errors.

- Each constraint appears exactly once in Databricks’ system catalog; no duplicate rows are returned by the _get_existing_constraints.sql macro.

### Screenshots and log output
```sql
Database Error in model entity_c (src/models/gold/entity_c.sql)
  Database Error
    [SCALAR_SUBQUERY_TOO_MANY_ROWS] More than one row returned by a subquery used as an expression. SQLSTATE: 21000
    == SQL (line 18, position 31) ==
        AND kcu.constraint_name = (
                                  ^
          SELECT constraint_name
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          FROM `gold`.information_schema.table_constraints
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          WHERE table_catalog = 'gold'
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            AND table_schema = 'data'
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            AND table_name = 'entity_c'
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            AND constraint_type = 'FOREIGN KEY'
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        )
    ^^^^^
```    

### System information
**The output of `dbt --version`:**
```
Core:
 - installed: 1.9.5

Plugins:
 - databricks: 1.10.2
```

**The operating system you're using:**
```
Windows 11
```

**The output of `python --version`:** ```Python 3.11.9```

### Additional context
This issue is not reproducible with **dbt-databricks 1.10.1** (and earlier *1.9.x releases*); it appears only after upgrading to version **1.10.2**.
