### ISSUE TITLE
1.10.2 forces lowercase `location_root` in dbt run config with no option to override

### ISSUE THREAD

**Issue by tom-webber** [databricks/dbt-databricks#1037]
### Describe the bug
Passing a case sensitive `location_root` string (including non-lower-case character) value to `dbt run`'s config leads to external location errors as the `location_root` is `.casefold()`'d into an all lower-case string for **new table** materialisation using `incremental` materialisation.

This appears to be a result of [this change](https://github.com/databricks/dbt-databricks/compare/v1.10.1...v1.10.2#diff-eda3da45eb40c9af29bd449e037819d31f7e2b3fb2e48e8f63ab7878cca76169R31-R48) introduced in the new `dbt/adapters/databricks/parse_model.py` file, which forces `location_root` to be `casefold()`ed.

### Steps To Reproduce

1.  Initialize a new dbt project:
    ```bash
    dbt init my_dbt_project
    cd my_dbt_project
    ```

2.  Configure `dbt_project.yml`:
    Update `dbt_project.yml` to use the `databricks` adapter and define a profile. Add a `vars` section to specify a mixed-case `location_root`.

    ```yaml
    name: 'my_dbt_project'
    version: '1.0.0'
    config-version: 2

    profile: 'default'

    models:
      my_dbt_project:
        +materialized: incremental
        +location_root: "s3://your-bucket/MyMixedCasePath/"
    ```

3.  Configure `profiles.yml`:
    Ensure `~/.dbt/profiles.yml` (or project-specific `profiles.yml`) has a Databricks connection configured:

    ```yaml
    default:
      target: dev
      outputs:
        dev:
          type: databricks
          host: "{databricks-host}.cloud.databricks.com"
          http_path: "/sql/1.0/warehouses/{warehouse-id}"
          token: "{dapiXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX}"
          threads: 4
          schema: "{dbt_test_schema}" # schema you can write to
    ```

4.  Create an incremental model (`models/my_incremental_model.sql`):

    ```sql
    -- models/my_incremental_model.sql
    {{
      config(
        materialized='incremental',
        on_schema_change='append_new_columns',
        incremental_strategy='append',
        file_format='parquet',
        location_root="s3://your-bucket/MyMixedCasePath/"
      )
    }}

    SELECT
      1 as id,
      'some_value' as data,
      current_timestamp() as loaded_at

    {% if is_incremental() %}

      -- this filter will only be applied on an incremental run
      -- (uses > to include records whose loaded_at is after the max loaded_at from the existing table)
      WHERE loaded_at > (select max(loaded_at) from {{ this }})

    {% endif %}
    ```

5.  Set up your S3 bucket and Databricks External Location:
    *   Ensure you have an S3 bucket (e.g., `s3://your-bucket/`).
    *   In Databricks, create an External Location that points to `s3://your-bucket/MyMixedCasePath/` (with the exact mixed casing). **Do NOT create an external location for `s3://your-bucket/mymixedcasepath/`**. This is crucial to reproduce the "No parent external location" error.

6.  Run the dbt model:
    Execute the dbt run command, explicitly passing the mixed-case `location_root`.

    ```bash
    dbt run 
    ```

7.  Observe the error:
    When dbt attempts to create the table for the first time, it will try to use a path like `s3://your-bucket/mymixedcasepath/` (all lowercase) due to the `.casefold()` behaviour. Since no external location is defined for this lowercase path, Databricks will raise an error similar to:
    ```
    Database Error in model my_incremental_model (models/my_incremental_model.sql)
      [NO_PARENT_EXTERNAL_LOCATION_FOR_PATH] No parent external location was found for path 's3://your-bucket/mymixedcasepath/your-table-name'. Please create an external location on one of the parent paths and then retry the query or command again.
    ```

    If you were to then create an external location for `s3://your-bucket/mymixedcasepath/` and re-run, the command would succeed, but the data would be written to the lowercase path, not the intended mixed-case path.

### Expected behaviour
A mixed-case string passed to config `location_root` should be preserved in the generated SQL. `case_sensitive` should be `True` by default or a breaking change issued if a change in default behaviour is desired.

### Screenshots and log output

```
Database Error in model [model_name] ([model_path])
  [NO_PARENT_EXTERNAL_LOCATION_FOR_PATH] No parent external location was found for path 's3://{bucket}/{case_sensitive_key}'. Please create an external location on one of the parent paths and then retry the query or command again
```

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.9.5
  - latest:    1.9.5

Plugins:
  - databricks: 1.10.2
  - spark:      1.9.2
```

**The operating system you're using:**
databricks runtime 12.2 LTS

**The output of `python --version`:**
3.9.21
