### ISSUE TITLE
Column comments broken for streaming tables

### ISSUE THREAD

**Issue by ericj-db** [databricks/dbt-databricks#1049]
### Describe the bug
Using column comments with streaming tables results in an dbsql error

### Steps To Reproduce
```
version: 2

models:
  - name: some_model
    config:
      materialized: streaming_table
    columns:
      - name: id
        description: Unique id to identify the record
```

### Expected behavior
Materialized streaming table should have column comment persisted
