### ISSUE TITLE
on sql-warehouse incremental models always replace all the data

### ISSUE THREAD

**Issue by AntonPeniaziev** [databricks/dbt-databricks#219]
### Describe the bug

Im running a simple model:
```
{{ config(
  materialized = 'incremental',
    incremental_strategy='merge',
  file_format = 'delta',
    unique_key='h3_10',
) }}

select "h3rferfre5" as h3_10
```

I found that when using sql-warehouse:
```
sql-serverless:
  outputs:
    dev:
      host: **
      http_path: **
      schema: hive_metastore.tube_silver_prod
      threads: 1
      token: **
      type: databricks
  target: dev
```

The model is always executes:
```
create
or replace table hive_metastore.tube_silver_prod.my_fi...
```

as a result all the data is deleted and replaced.

When running the same model with a profile that uses an interactive cluster
```
cluster:
  outputs:
    dev:
      host: ***
      http_path: ***
      schema: tube_silver_prod
      threads: 1
      token: ***
      type: databricks
  target: dev
```

the result query is as expected:
`merge into tube_silver_prod.my_first_dbt_model as DBT_INTERNAL_DEST...`

the result is merged/appended as expected

Plugins:
  - databricks: 1.2.1 - Update available!
  - spark:      1.2.0 - Update available!
Python 3.8.13

Thanks
