### ISSUE TITLE
Sync Unity meta data with dbt model.yml metadata on run

### ISSUE THREAD

**Issue by EtherJfox** [databricks/dbt-databricks#247]
### Describe the feature
dbt tracks table meta data (name, description, column name, column description) in the model.yml. Unity also has these meta data labels. A dbt run should sync the metadata to Unity.

### Describe alternatives you've considered
Writing my own python notebook to parse manifest.json for these meta data items and iterating over it myself to add the metadata to Unity.

### Additional context
Both the create and alter statement have the ability to add table comments at table or column level.

### Who will this benefit?
Everyone using model documentation. We're creating dbt documentation as we go, Unity should benefit.

### Are you interested in contributing this feature?
I have my own method of syncing the data but I don't have any time in the foreseeable future to look into how to get this working inside the dbt-databricks framework.

**Comment by ueshin** [comment]
Hi @EtherJfox,

Could you elaborate what kind of metadata you mean?
Are they different from what `persist_docs` does?

**Comment by EtherJfox** [comment]
Didn't know the feature existed. Looks like I'm getting the table level comment on some tables, but not others, and no column comment.

Sample config

version: 2

```
models:
  - name: finance_datamart__dim_date_accounting
    description: A date dimension used in the Finance data model representing accounting periods
    columns:
      - name: date_key
        description: An integer representation of the date
    config:
      enabled: true
      file_format: delta
      +persist_docs:
        relation: true
        columns: true  
```
