### ISSUE TITLE
[bug]   dbt-databricks v1.0.0 did not update dba-spark ('str' object has no attribute '_message')

### ISSUE THREAD

**Issue by drernie** [databricks/dbt-databricks#30]
### Describe the bug
After upgrading to v1.0.0 of dbt, I re-installed dbt-databricks. Now I get this error:
>   >Runtime Error
  'str' object has no attribute '_message'

### Steps To Reproduce
dbt debug -t http

### Expected behavior
[OK]

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.
```
 % dbt debug -t http
01:07:05  Running with dbt=1.0.0
dbt version: 1.0.0
python version: 3.9.9
python path: /Users/nauto/Developer/dbt/dbt-env/bin/python3
os info: macOS-12.0.1-x86_64-i386-64bit
Using profiles.yml file at /Users/nauto/.dbt/profiles.yml
Using dbt_project.yml file at /Users/nauto/Developer/dbt/dbt_project.yml

Configuration:
  profiles.yml file [OK found and valid]
  dbt_project.yml file [OK found and valid]

Required dependencies:
 - git [OK found]

Connection:
  host: nauto-biz-prod-us.cloud.databricks.com
  port: 443
  cluster: 1004-233546-lager607
  endpoint: None
  schema: default
  organization: 0
  Connection test: [ERROR]

1 check failed:
dbt was unable to connect to the specified database.
The database returned the following error:

  >Runtime Error
  'str' object has no attribute '_message'

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile
```
### System information
**The output of `dbt --version`:**
```
dbt --version
installed version: 1.0.0
   latest version: 1.0.0

Up to date!

Plugins:
  - databricks: 1.0.0
  - spark: 0.21.0
```

AHA.  That was it. I uninstalled dbt-spark and re-installed it back with v1, and it works.

dot-core complained about outdated modules but dbt-databricks did not

**Comment by ueshin** [comment]
You need to set the connection configuration for dbt-databricks:

```
your_profile_name:
  target: dev
  outputs:
    dev:
      type: databricks
      schema: [database/schema name]
      host: [your.databrickshost.com]
      http_path: [/sql/your/http/path]
      token: [dapiXXXXXXXXXXXXXXXXXXXXXXX]
```

See the `Step 3.3` for more detail: https://docs.databricks.com/dev-tools/dbt.html#step-3-create-a-dbt-project-and-specify-and-test-connection-settings
