### ISSUE TITLE
Character encoding changes upon seeding

### ISSUE THREAD

**Issue by jdbodyfelt** [databricks/dbt-databricks#332]
### Describe the bug
A CSV file that has UTF-8 encoding is seeded with `dbt seed`. Upon review of the load, the column encoding has appeared to change. 

### Steps To Reproduce
Create a CSV with non-standard non-Roman UTF-8 characters (Arabic, Greek, etc.) and try seeding it. 

### Expected behavior
I expect a CSV seeds exactly what is inside of it, ESPECIALLY strings. 

### Screenshots and log output
CSV:
![image](https://user-images.githubusercontent.com/11973991/235822152-baedfa2c-81d6-4d22-9789-afbed5184e97.png)
Injection Result:
![image](https://user-images.githubusercontent.com/11973991/235822675-ee98a91c-551c-4fec-9c6b-b3d1c1a1b4b7.png)

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.4.6
Plugins:
  - databricks: 1.4.3 
```

**The operating system you're using:**   
Ubuntu 22.04.1 LTS

**The output of `python --version`:**
Python 3.10.6
### Additional context
It would be great to have a seeds configuration option for column encoding, e.g. 
```
seeds:
   - name: <tableName>
      config:
         columns:
             - name: <columeName>
                dtype: <columnDatatype>
                encoding: <columnEncoding if STRING or VARCHAR>
```
