### ISSUE TITLE
Choose different compute for SQL models

### ISSUE THREAD

**Issue by mvdwielen** [databricks/dbt-databricks#333]
I would like to be able to run some SQL models in my DBT project on different compute than other models. I noticed this is possible for Python models but I can't find a config setting for SQL models.

**Comment by owenprough-sift** [comment]
Duplicate of #59?

**Comment by susodapop** [comment]
Is dbt-databricks the right place to implement this feature? It seems more appropriate to add it to dbt-core so that every 
 adapter (including dbt-databricks) will benefit from the change.

**Comment by owenprough-sift** [comment]
This issue is also conceptually related to #321

**Comment by andrefurlan-db** [comment]
Unfortunately, it makes no difference for us :-(. A warehouse is a managed set of clusters with queues, retries, etc that makes it suitable for SQL workflows.

**Comment by benc-db** [comment]
We are working on improving our connection stack generally, including making this feature possible, and are aiming to deliver before year end.  Sorry this taking so long; connection management is shared between our adapter and dbt-core in a way that makes this feature more difficult than adding materialization features.

**Comment by benc-db** [comment]
Hi all, thank you for your patience.  We have just release 1.7.2b2, a beta build which includes this feature.  **DO NOT RELY ON THIS FEATURE YET FOR PRODUCTION WORKLOADS**. Find the instructions below, and please file Github Issues for any bugs you encounter.

# Instructions for Compute-per-Model

With release 1.7.2b2 of the dbt-databricks adapter, we are testing out allowing users to specify their compute on a per model basis.  To do this we have added a `compute` section to the profile to specify the named computes available to be used by the project for a given output.

```
Your_profile_name:
    target: dev
    outputs:
        dev:
            type: databricks
            catalog: [optional catalog name if you are using Unity Catalog]
            schema: [schema name] # Required        
            host: [yourorg.databrickshost.com] # Required        
            http_path: [/sql/your/http/path] # Required        
            compute:
                Compute1:                 
                    http_path: ‘/sql/your/http/path’                        
               Compute2:
                    http_path: ‘/some/other/path’                    
            ...
```
 
The new compute section of the profile will be a map of user chosen names to objects with an http_path property.  Each compute is keyed by a name which is used in the model definition/configuration to indicate which compute you wish to use for that model/selection of models. Note, you need to have the same set of names for compute across your outputs, though you may supply different http_paths, allowing you to use different computes in different deployment scenarios.

## Specifying the Compute for a Model

Specifying the compute for a model as part of its configuration can be done in multiple ways.  In the project yml the warehouse can be specified for types of artifacts (i.e. model, seed, snapshot, etc) or for all the models in a given directory.

```
name: my_project
version: 1.0.0

...

models:
  +databricks_compute: "Compute1"    # use the `Compute1` warehouse for all models in the project...
  my_project:
    clickstream:
      +databricks_compute: "Compute2"    # ...except for the models in the `clickstream` folder, which will use the `Compute2` warehouse.

snapshots:
  +databricks_compute: "Compute1"    # all Snapshot models are configured to use the `Compute1` warehouse.
```

For an individual model the warehouse can be specified in the model information in the schema yml file.

```
models:
  - name: table_model
    dbsource: another_db_source
    config:
        databricks_compute: Compute1
    columns:
      - name: id
        data_type: int
```

Alternatively the warehouse can be specified in the config block of a model's SQL file.

```
{{config(materialized='table', databricks_compute='Compute1')}}
select * from {{ ref('seed') }}
```

## FYI

In the absence of a specified compute, we will default to the compute specified by http_path in the top level of the output section in your profile.  This is also the compute that will be used for tasks not associated with a particular model executing a model, such as gathering metadata for all tables in a schema.

For now, if you want to validate that the specified compute is being used, in your dbt.log you will see this statement

`Databricks adapter: Using default compute resource.`

whenever the default compute is selected for a task.  When a non-default compute is selected you will see a line like this:

`Databricks adapter: Using compute resource <compute name>.`

Currently these lines are associated only with a Thread-Id, so to verify which operation they are being used with, look at the one or two previous log statements with that matching thread id.
