### ISSUE TITLE
Support UC external volumes

### ISSUE THREAD

**Issue by kdazzle** [databricks/dbt-databricks#361]
### Describe the feature
Similar to the [dbt-external-tables](https://github.com/dbt-labs/dbt-external-tables) package, it would be nice to be able to specify external volumes in the yaml.

Maybe something like the following?

```
# sources.yml

version: 2

sources:
  - name: my_schema_name
    tables:
      - name: product
         description: "Product table"
         external:
           location: s3://product-data/v1
           using: delta
    volumes:
      location: s3://...
      comment: "External volume in dbt"
      grants:
        read: 
          - read-group-1
```

### Describe alternatives you've considered
I've played around with overriding some of the functionality locally, but would prefer to not do that.

I've also considered extending external-tabels and nesting it under tables.external, but that would mean creating a table (unless that functionality is overridden too), which would clash with the volume. It also doesn't make much sense hierarchically.

### Additional context
Please include any other relevant context here.

### Who will this benefit?
Anyone who wants to define UC volumes in dbt instead of through Terraform or SQL notebooks

### Are you interested in contributing this feature?
Yes
