### ISSUE TITLE
Support for generated columns

### ISSUE THREAD

**Issue by ValdarT** [databricks/dbt-databricks#393]
Would like to use [generated columns](https://docs.databricks.com/delta/generated-columns.html) in our dbt models.

The use case is to have partitioning based on generated column from a timestamp field so end users wouldn't need to worry about the partitioning scheme (as the partition filters would propagate through when end users filter on the base timestamp field).

**Comment by benc-db** [comment]
@ValdarT do you have a proposal for how users would opt-in to this behavior?

**Comment by ValdarT** [comment]
Ideally under column definition, e.g., through the `meta` field
```
models:

  - name: foo
    config:
      partition_by: dt
    columns:
      - name: createdAt
      - name: dt
        data_type: date
        meta:
          generation_expression: "CAST(createdAt AS DATE)"
```

But if better implemented as new a databricks-specific config then perhaps something like this

```
models:

  - name: foo
    config:
      generated_columns:
        - name: dt
          data_type: date
          expression: "CAST(createdAt AS DATE)"
      partition_by: dt
```
