### ISSUE TITLE
dbt logs not getting generated for dbt commands in Databricks (dbt-databricks)

### ISSUE THREAD

**Issue by abhishek-7781** [databricks/dbt-databricks#423]
### Describe the bug
I'm running a dbt project (which reads data from ADLS and writes back to ADLS) using a Databricks Workflow. When I configure **log-path** in **dbt-project.yml** to generate dbt logs in a specific DBFS location, dbt is generating logs only for **dbt deps** command and not for **dbt debug**, **dbt run** or **dbt test** etc.
Although it works fine while running it from local Python virtual environment (through VSCode).

### Steps To Reproduce
1. Setup a dbt project for Databricks
2. profiles.yml
```
project_name:
    output:
        databricks_job:
              type: databricks
              method: http
              threads: 4
              schema: "{{ env_var('target_schema') }}"
              host: "{{ env_var('hostname') }}"
              http_path: "{{ env_var('http_path') }}"
              token: "{{ env_var('token') }}"
```
3. dbt_projectyml
```
name: 'project_name'
version: '1.0.0'
config-version: 2
profile: 'profile_name'
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros","dbt_packages/shared_repo_name/macros"]
snapshot-paths: ["snapshots"]

target-path: /dbfs/dbt-databricks/target/
log-path: /dbfs/dbt-databricks/logs/
```
4. Run the following commands
```
dbt deps
dbt debug
dbt run --select mode_name
dbt test --select model_name
```

### Expected behavior
dbt should have generated logs for all the above mentioned commands in the **./logs/dbt.log** file.

### System information
```
- Environment/Platform: Databricks
- Python: 3.9.5
- dbt-core: 1.3.5
- dbt-databricks: 1.3.2
- databricks-sql-connector: 2.1.0
```

### Additional context
System information of the local machine where this works fine:
```
- Python: 3.10.9
- dbt-core: 1.3.5/1.6.0
- dbt-databricks: 1.3.2/1.6.1
- databricks-sql-connector: 2.7.0
```

### Error screenshots
![image](https://github.com/databricks/dbt-databricks/assets/141800574/f7594ace-095d-481b-bfa2-fc0fd9e93c8b)
![image](https://github.com/databricks/dbt-databricks/assets/141800574/06415134-7f65-401b-9803-fb5aaac9f086)
![image](https://github.com/databricks/dbt-databricks/assets/141800574/c913dcf3-a6a6-4dfb-8656-88bc8b6b1376)

![image](https://github.com/databricks/dbt-databricks/assets/141800574/e17da79d-8967-42f5-865f-7227f13dc89b)
