### ISSUE TITLE
ServicePrinicipal Authentication (OAuth) doesn't work while running dbt jobs on Databricks

### ISSUE THREAD

**Issue by abhishek-7781** [databricks/dbt-databricks#433]
### Describe the bug
While running a dbt project (which reads data from ADLS and writes back to ADLS) using a Databricks Workflow, the authentication with Databricks Cluster using a Personal Access Token is working but authentication using Service Principal (OAuth) isn't working.

As mentioned in the [dbt documentation](https://docs.getdbt.com/docs/core/connect-data-platform/databricks-setup?tokenoauth=oauth#authentication-parameters):
The dbt-databricks adapter supports both [token-based authentication](https://docs.getdbt.com/docs/core/connect-data-platform/databricks-setup?tokenoauth=token#examples) and [OAuth client-based authentication](https://docs.getdbt.com/docs/core/connect-data-platform/databricks-setup?tokenoauth=oauth#examples).

### Steps To Reproduce
1. Setup a dbt project for Databricks
2. profiles.yml
```
project_name:
    output:
        databricks_job:
              type: databricks
              method: http
              threads: 4
              schema: target_schema
              host: "{{ env_var('hostname') }}"
              http_path: "{{ env_var('http_path') }}"
              client_id: "{{ env_var('client_id') }}"
              client_secret: "{{ env_var('client_secret') }}"
              auth_type: oauth
```

### Expected behavior
Connection with the Databricks Cluster should have successfully established.

### Screenshots and log output
**1. While using dbt-databricks==1.6.1, error "_No valid authentication settings!_" occurs.**
![image](https://github.com/databricks/dbt-databricks/assets/141800574/159ed207-5a6f-4e05-b7be-c61c2effb3c2)

**2. While using dbt-databricks==1.3.2, error "_The config token is required to connect to Databricks_" occurs.**
![image](https://github.com/databricks/dbt-databricks/assets/141800574/1801684d-48fa-40ac-b78a-d7859182d2de)

### System information
**When using the following `dbt --version`, error "No valid authentication settings!" occurs.**
```
Core:
  - installed: 1.6.0
  - latest:    1.6.1 - Update available!
Plugins:
  - databricks: 1.6.1 - Update available!
```
**When using the following `dbt --version`, error "The config token is required to connect to Databricks" occurs.**
```
Core:
  - installed: 1.3.5
  - latest:    1.6.1 - Update available!
Plugins:
  - databricks: 1.3.2 - Update available!
```

**The operating system you're using:**
```
Databricks Workflow (Job Cluster)
Driver: Standard_DS3_v2 · Workers: Standard_DS3_v2 · 0 workers · 12.2 LTS (includes Apache Spark 3.3.2, Scala 2.12)
```

**The output of `python --version`:**
`python version: 3.9.5`
