### ISSUE TITLE
The tblproperties are not applied when using Python Model to create a table

### ISSUE THREAD

**Issue by csimplestring** [databricks/dbt-databricks#584]
### Describe the bug
When using the python model, the tblproperties in config is not applied. The final result table does not contain those table properties. 

### Steps To Reproduce
Under the `models/data.yml`, i set the following configurations
```
config:
    partition_by:
    - event_date
    tblproperties:
        delta.compatibility.symlinkFormatManifest.enabled: false
        delta.minReaderVersion: 2
        delta.minWriterVersion: 7
        delta.columnMapping.mode: name
        delta.enableIcebergCompatV2: true
        delta.universalFormat.enabledFormats: iceberg
```
In the `models/data.py`, it is
```
from pyspark.sql import functions as func

def model(dbt, session):

    df = dbt.source("data", "accounts")
    # do some transformation
    return df
```

then I run `dbt run --select data`

### Expected behavior
Those table properties should be respected.

### Screenshots and log output
<img width="757" alt="Screenshot 2024-02-14 at 11 29 44" src="https://github.com/databricks/dbt-databricks/assets/5042273/fb865c54-e9f7-40c2-b190-d831a97288a3">
As you can see, only the default table properties are used, the new properties are not used at all.

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.7.7
  - latest:    1.7.7 - Up to date!

Plugins:
  - databricks: 1.7.3 - Update available!
  - spark:      1.7.1 - Up to date!
```

**The operating system you're using:**
Linux
**The output of `python --version`:**
Python 3.10.7

### Additional context
I am using the Azure Databricks, DBR is 14.3 LTS.
