### ISSUE TITLE
[bug] Composite primary key constraint fails

### ISSUE THREAD

**Issue by kmarq** [databricks/dbt-databricks#676]
### Describe the bug
Unable to apply a multiple column primary key

### Steps To Reproduce
Simple model:
```
select
'a' as col_1,
'b' as col_2
```

adding col_1 as the PK works as expected.
```
models:
  - name: model_a
    config:
      contract:
        enforced: true
    columns:
      - name: col_1
        data_type: string
        constraints:
          - type: not_null
          - type: primary_key
      - name: col_2
        data_type: string
        constraints:
          - type: not_null
```

```
models:
  - name: model_a
    config:
      contract:
        enforced: true
    columns:
      - name: col_1
        data_type: string
        constraints:
          - type: not_null
      - name: col_2
        data_type: string
        constraints:
          - type: not_null
    constraints:
      - type: primary_key
        columns: [col_1, col_2]   
```

However, updating to try and use a composite primary key does not work.  In the second scenario it tries to create the primary key 
>alter table `model_a` add constraint 0a36b673f037eb84f703cefef2531521 primary key(col_1, col_2);

However, it is not setting the two columns as not_null first and so creation of the PK fails.
>: Cannot create the primary key `0a36b673f037eb84f703cefef2531521` because its child column(s) `col_1` is nullable. Please change the column nullability and retry.

### Expected behavior
The columns are set to NOT NULL before the primary key is applied

### Screenshots and log output
```
`       create or replace table `model_a`
 
    using delta
      as
    select col_1, col_2
    from (
select
'a' as col_1,
'b' as col_2
    ) as model_subq`

alter table `model_a` add constraint 0a36b673f037eb84f703cefef2531521 primary key(col_1, col_2);
      
18:59:38 Databricks adapter: Cursor(session-id=01ef186d-6818-15d1-b37f-1642bf4c4ff9, command-id=Unknown) - Closing cursor
18:59:38 Databricks adapter: Exception while trying to execute query
/* {"app": "dbt", "dbt_version": "1.7.14", "dbt_databricks_version": "1.7.15", "databricks_sql_connector_version": "2.9.6", "profile_name": "user", "target_name": "dev", "node_id": "model.databricks_analytics_dbt.model_a"} */

        alter table `model_a` add constraint 0a36b673f037eb84f703cefef2531521 primary key(col_1, col_2);
      
: Cannot create the primary key `0a36b673f037eb84f703cefef2531521` because its child column(s) `col_1` is nullable. Please change the column nullability and retry.
```

### System information
**The output of `dbt --version`:**
```
18:59:18 Running with dbt=1.7.14
18:59:18 Registered adapter: databricks=1.7.15
```

DBT Cloud

**The output of `python --version`:**
