### ISSUE TITLE
Foreign Key constraint error: No parent table defined for foreign key

### ISSUE THREAD

**Issue by PtrckGdwn** [databricks/dbt-databricks#784]
### Describe the bug
When trying to create a foreign key constraint on a relation using the `parent` and `parent_columns` constraint attributes, I am getting an error at run time: `No parent table defined for foreign key` which is followed by a trace.

### Steps To Reproduce
I have configured the model's schema like so:

```
  - name: example__child_table
    constraints:
      - type: primary_key
        name: pk_example__child_table
        columns: ["id"]
      - type: not_null
        columns: ["id", "name", "parent_id"]
      - type: foreign_key
        name: fk_example__child_table_1
        columns: ["parent_id"]
        parent: parent_table
        parent_columns: ["id"]
    columns:
      - name: id
      - name: name
      - name: parent_id
```

When running the project this results in the error message described above.

### Expected behavior
The foreign key sql should be generated, and assume all else is good (e.g., the parent_table has a primary key) the foreign key should be created.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**The output of `dbt --version`:**
```
Running with dbt=1.8.6
Registered adapter: databricks=1.8.5
```

**The operating system you're using:**
Running as a dbt task in a Databricks workflow. 
Compute: Single node: Standard_DS3_v2 · DBR: 14.3.x-photon-scala2.12

### Additional context
The traditional `expression` method of creating a foreign key works as documented, but I would like to avoid using it because it has a hard coded schema name. The `parent` + `parent_columns` method assumes that the parent table is in the same schema as the child, which for me is true.
