### ISSUE TITLE
Snapshot + uniform is broken since todays databricks release

### ISSUE THREAD

**Issue by jelmerk** [databricks/dbt-databricks#819]
### Describe the bug

We have a number of dbt snapshot models and use this configuratrion that configures the output tables to be used with uniform

```
snapshots:
  foo_source_product:
    foo:

      +target_schema: foo_source_product_snapshots

      +post-hook:
        - "vacuum {{ this }}"

      +tblproperties:
        delta.columnMapping.mode: name
        delta.minReaderVersion: 3
        delta.minWriterVersion: 7
        delta.universalFormat.enabledFormats: iceberg
        delta.enableIcebergCompatV2: true
        delta.feature.timestampNtz: supported
```

After todays Databricks release in the US all of our snapshot builds started failing with the following error

```
Table properties delta.universalFormat.enabledFormats and delta.universalFormat.v1Formats.location are only allowed for managed Delta tables.
```

This is because as part of the snapshot process [dbt-databricks creates a view](https://github.com/databricks/dbt-databricks/blob/6bcd4eadcc5bef37719b869048e1f1dfa312f6ae/dbt/include/databricks/macros/materializations/snapshot.sql#L1)

And you end up with something like

```
create
or replace view `data_platform_prd`.`foo_source_product_snapshots`.`my_table__dbt_tmp`
tblproperties (
  'delta.columnMapping.mode' = 'name',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7',
  'delta.universalFormat.enabledFormats' = 'iceberg',
  'delta.enableIcebergCompatV2' = 'True',
  'delta.feature.timestampNtz' = 'supported'
) as select 1 as test;
```

Which databricks now rejects because the view is not a managed delta table. Before today's release this worked fine

### System information
**The output of `dbt --version`:**
```
dbt --version
Core:
  - installed: 1.8.7
  - latest:    1.8.7 - Up to date!

Plugins:
  - databricks: 1.8.6 - Up to date!
  - spark:      1.8.0 - Up to date!
```

**The operating system you're using:**
Mac os / linux inside of docker

**The output of `python --version`:**
Python 3.11.4
