### ISSUE TITLE
dbt enforced data_type checks doesn't check complex data types in Databricks

### ISSUE THREAD

**Issue by zeljkostojkovic** [databricks/dbt-databricks#880]
### Describe the bug
When I define model like following, and execute `dbt run `command, command will succeed if `metadata` field is really of type `STRUCT`, but underlying keys in the struct and their corresponding data types won't be checked.

```yaml
models:
  - name: test_model
    config:
      contract:
        enforced: true
        alias_types: false
    columns:
      - name: id
        data_type: STRING

      - name: metadata
        data_type: STRUCT<property_1 STRING, property_2 STRING>
```

SQL model:

```sql
  select
    id,
    CAST(metadata AS STRUCT<property_3 STRING> as metadata
  from {{ source('source', 'source_table') }}
```

I've noticed this when I tried testing and changing my `data_type` from STRUCT to MAP. In that case dbt run command retuned this error:

![image](https://github.com/user-attachments/assets/ef84db78-e58c-4250-bd5d-b1610bf93ed7)

`definition_type` and `contract_type` are not taking into account values inside complex/nested structures.

### Steps To Reproduce
Using model configuration and similar SQL command (that contains `STRUCT` field) from above, execute `dbt run` command. Command will succeed no matter what underlying struct configuration is setup in `data_type` field (works with setting just `STRUCT<>`).

### Expected behavior
I would expect for dbt to fail if `contract` is enforced, and complex data types like `ARRAY`, `MAP` and `STRUCT` are not fully described, or even better under `contract` configuration to have `check_complex_types` boolean field which can decide whether to check nested structures or not.

### System information
**The output of `dbt --version`:**
```
dbt Cloud CLI - 0.38.15
dbt-databricks: 1.8.7
```

**The operating system you're using:**
macOS 15.1.1

**The output of `python --version`:**
Python 3.11.9
