### ISSUE TITLE
Specifying compute for Python models

### ISSUE THREAD

**Issue by vzhyruk** [databricks/dbt-databricks#890]
### Describe the bug
[https://docs.getdbt.com/reference/resource-configs/databricks-configs#specifying-compute-for-python-models](https://docs.getdbt.com/reference/resource-configs/databricks-configs#specifying-compute-for-python-models)
Documentation says:
_"When you specify your databricks_compute for a python model, you are currently only specifying which compute to use when running the model-specific SQL. If you wish to use a different compute for executing the python itself, you must specify an alternate compute in the config for the model."_

This behaviour is misleading and not intuitive. And also requires to additionally specify same computes several times in profiles and model configurations which breaks the usage of different profiles and targets in your project.

### Steps To Reproduce
1. Secondary databricks compute is set as all_purpose compute
profiles.yml:
```
<profile>:
  target: <target>
  outputs:
    <target>:
      type: databricks
      ..........
      http_path: <default_compute>
      compute:
        secondary_compute:
          http_path: <secondary_all_purpose_compute>
```
2. Compute is set for subfolder with models which include python models as well.
dbt_project.yml:
```
<subfolder>:
      .........
      +databricks_compute: secondary_compute
```
3. Run models
4. Python models are executed against default compute regardless of the 'databricks_compute' config

### Expected behavior
When 'databricks_compute' is set for python models and it is all purpose compute they should use it for both Python and SQL parts.
