### ISSUE TITLE
Configure custom catalog in dbt_project.yml

### ISSUE THREAD

**Issue by Korijn** [databricks/dbt-databricks#926]
### Describe the bug
I'm trying to implement a project variable to load sources from an alternative catalog. It works in properties.yml files, but it doesn't work in dbt_project.yml.

### Steps To Reproduce
This works:

```yml
# sources/some_source.yml
sources:
  - name: bronze
    catalog: "{{ var('source_catalog', target.catalog) }}"
```

This does **not** work:
```yml
# dbt_project.yml
sources:
  acme:
    +catalog: "{{ var('source_catalog', target.catalog) }}"
```

Note: no errors, the option is just silently ignored when I run with `dbt compile --vars '{"source_catalog": "foobar"}'`

### Expected behavior
I would expect the catalog config in `dbt_project.yml` to be effective just like the one in `sources/some_source.yml`.

### Screenshots and log output
N/A

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.9.1
  - latest:    1.9.2 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - spark:      1.9.0 - Up to date!
  - databricks: 1.9.1 - Update available!

  At least one plugin is out of date with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

**The operating system you're using:**
Debian (inside a docker dev container on WSL)

**The output of `python --version`:**
`Python 3.12.8`
