### ISSUE TITLE
Support for Multiple Actions in MERGE and Column-Specific Updates

### ISSUE THREAD

**Issue by liangonli** [databricks/dbt-databricks#949]
### Describe the feature
Currently, in dbt-databricks v1.9.7, the incremental merge strategy does not fully leverage the flexibility of Databricks' MERGE INTO statement. 

According to the [Databricks documentation](https://docs.databricks.com/aws/en/sql/language-manual/delta-merge-into), it is possible to:

1. Define multiple MATCHED conditions with different actions (e.g., UPDATE, DELETE), each with its own condition.
2. Define multiple NOT MATCHED BY SOURCE conditions with different actions (e.g., DELETE, UPDATE).
3. Specify which columns to update in an UPDATE action instead of updating all columns by default.

However, in dbt-databricks v1.9.7, these capabilities are not fully supported:

It is not possible to specify multiple MATCHED or NOT MATCHED BY SOURCE actions.
The action for MATCHED is not configurable.
We cannot specify which columns should be updated in an UPDATE action.

### Describe alternatives you've considered
Manually implementing a MERGE INTO statement using a custom post-hook, but this reduces the benefits of dbt’s incremental logic and maintainability.
Using a two-step process: updating/deleting records separately by 2 merging, but this introduces additional complexity and performance overhead.

### Additional context
Databricks supports defining multiple conditions within MERGE INTO, making it more flexible for incremental processing. Supporting these features in dbt-databricks would allow users to take full advantage of this flexibility and optimize their data pipelines.

### Who will this benefit?
Data engineers & analysts using incremental models in dbt-databricks.
Use cases where for example:
1. Different update conditions need to be applied to different rows.
2. Certain rows should be deleted instead of updated based on specific criteria.
3. Only specific columns should be updated to prevent unnecessary writes.

**Comment by oberalppaolof** [comment]
Absolutely agree and support this request!
It will be solve a lot of problems in the delete actions.

**Comment by benc-db** [comment]
@mi-volodin is this truly missing or have I not documented appropriately?

**Comment by mi-volodin** [comment]
@benc-db 

TL;DR - it's truly missing.

Here's my rationale. From the docs we have the following description for the allowed blocks

```
     WHEN MATCHED [ AND matched_condition ] THEN matched_action |
     WHEN NOT MATCHED [BY TARGET] [ AND not_matched_condition ] THEN not_matched_action |
     WHEN NOT MATCHED BY SOURCE [ AND not_matched_by_source_condition ] THEN not_matched_by_source_action }
```

First, something that stemmed from prior-1.9 implementation was that
1. When `matched` it is always assumed to be update.
2. When `not matched` it is always `insert`.

That is easy to fix.

The not matched by source allows now both deletes and updates, so that's also kind of available already.

From this part

> Define multiple MATCHED conditions with different actions (e.g., UPDATE, DELETE), each with its own condition.

I assume that the following is meant

```sql
...
when matched and condition1 then delete
when matched and condition2 then update ...
...
```

I can take a look into it next week.

**Comment by oberalppaolof** [comment]
I have a real case that, with the current version 1.9 I can only solve with a delete via post-hook...
Change data feed: my source table is the result of ‘select * from table_changes(...)’. What I can't do is to define a matching condition “s._change_type = ‘delete’” and as action ”delete”
At the same time define add a matching condition “s.attribx != t.attribx” with action “update”. This way I would perform a single commit and it would be more performant.

I hope my real case could help you. 
Thanks

**Comment by mbahra** [comment]
Thank you for your answers.  
Our real use case is too complex to describe here, but here are 2 very simplified examples:

---

### 🔹 Example 1

**Target table (`target`)**:

| id | color |
|----|-------|
| 1  | blue  |
| 2  | red   |

**New records (`source`)**:

| id | color  |
|----|--------|
| 1  | purple |
| 2  | null   |
| 3  | green  |
| 4  | null   |

**Expected output**:  
We want to:
- Update the color if it's different from the target table (id = 1)
- Delete the row from the target table if `color` is null in the new records (id = 2)
- Insert rows whose id is not in the target table only if `color` is not null (id = 3 and 4)

| id | color  |
|----|--------|
| 1  | purple |
| 3  | green  |

**Configuration example**:

```yaml
unique_key: id
matched_delete_condition: source.color is null
matched_update_condition: source.color != target.color
not_matched_condition: source.color is not null
```

This only allows a single `matched_update_condition` - `matched_update_action` pair.  

To handle multiple such rules, we would need support for a list of dictionaries, for example:

```yaml
unique_key: id
matched:
  - matched_condition: source.color is null
    matched_action: DELETE  # delete row

  - matched_condition: source.color != target.color
    matched_action: UPDATE  # update all columns

not_matched_condition: source.color is not null
not_matched_action: INSERT *
```

Suggested config structure for `matched`:

```yaml
matched:
  - matched_condition: <condition or null>
    matched_action: UPDATE or DELETE or null (default: UPDATE)
    merge_update_columns: <list of columns or null> (default: "*")
    merge_exclude_columns: <list of columns or null>
  ...
```

---

### 🔹 Example 2

**Target table (`target`)**:

| id | color | date       | is_soft_deleted |
|----|-------|------------|-----------------|
| 1  | blue  | 2025-01-01 | false           |
| 2  | red   | 2010-01-01 | false           |

**New records (`source`)**:

| id | color | date       | is_soft_deleted |
|----|-------|------------|-----------------|
| 3  | green | 2025-01-02 | false           |

**Expected output**:  
We want to:
- Update rows not in source with `SET is_soft_deleted = true` if `current_date - date <= 10 years` (id = 1)
- Delete rows not in source if `current_date - date > 10 years` (id = 2)
- Insert rows not in target table (id = 3)

| id | color | date       | is_soft_deleted |
|----|-------|------------|-----------------|
| 1  | blue  | 2025-01-01 | true            |
| 3  | green | 2025-01-02 | false           |

**Configuration example**:

```yaml
unique_key: id
not_matched_by_source_delete_condition: current_date - date > 10 years
not_matched_by_source_update_condition: current_date - date <= 10 years
not_matched_by_source_update_action: SET is_soft_deleted = true
```

Again, we can only handle one `not_matched_by_source_update_condition` - `not_matched_by_source_update_action` pair.  

We would need support for a list of dictionaries like:

```yaml
unique_key: id
not_matched_by_source:
  - not_matched_by_source_condition: current_date - date > 10 years
    not_matched_by_source_action: DELETE

  - not_matched_by_source_condition: current_date - date <= 10 years
    not_matched_by_source_action: UPDATE SET is_soft_deleted = true
```

Suggested config structure for `not_matched_by_source`:

```yaml
not_matched_by_source:
  - not_matched_by_source_condition: <condition or null>
    not_matched_by_source_action: UPDATE EXPRESSION or DELETE or null (default: DELETE)
  ...
```

**Comment by jbrelle** [comment]
Would also love to see this feature implemented!

**Comment by liangonli** [comment]
Thanks for the examples. 

Do the answers above meet your needs ? @mi-volodin @benc-db

**Comment by mi-volodin** [comment]
Thanks for the examples provided. 
@mbahra Thank you for the config proposal. I need to look more carefully how to make it backwards compatible.

I am not sure I like the proposed dicts though, looks a little bulky. But I'll build on top of your proposal and will try to look into something like this first

```yaml
not_matched_by_source:
  - condition: current_date - date > 10 years
    action: DELETE

  - condition: current_date - date <= 10 years
    action: UPDATE SET is_soft_deleted = true
```

I would like to just have arrays, but maybe it will be too error-prone.
