### ISSUE TITLE
1.10.0a1 Quotes not applied to foreign/primary key constraints when using materialization V2

### ISSUE THREAD

**Issue by samuelberntzen** [databricks/dbt-databricks#965]
### Describe the bug
Materialization V2 breaks the constraints containing column names with special characters (æ,ø,å in our case), because columns quotations from the model configuration are ignored. For example:
```
models:
  - name: my_model
    config:
     contract:
       enforced: true
    columns:
      - name: speciål_char_pk
        data_type: string
        quote: true
        constraints:
          - type: not_null
          - type: primary_key

      - name: avfallshåndtering_fk
        data_type: string
        quote: true
        constraints:
          - type: foreign_key
            to: source("global", "dim_avfallshåndtering")
            to_columns: ["`avfallshåndtering_pk`"]
```

Will fail with error message
```
[INVALID_IDENTIFIER] The unquoted identifier speciål_char_pk is invalid and must be back quoted as: `speciål_char_pk`.
```

for primary key, and 

 ```
INVALID_IDENTIFIER] The unquoted identifier avfallshåndtering_fk is invalid and must be back quoted as: `avfallshåndtering_fk`.
```

for foreign key constraint

### Steps To Reproduce
1) Configure project to run materialization V2 in dbt_project.yml:
```
flags:
  use_materialization_v2: true
```
2) Create model with a foreign key column containing special characters that need to be quoted:
```
models:
  - name: my_model
    config:
     contract:
       enforced: true
    columns:
      - name: speciål_char_pk
        data_type: string
        quote: true
        constraints:
          - type: not_null
          - type: primary_key

      - name: avfallshåndtering_fk
        data_type: string
        quote: true
        constraints:
          - type: foreign_key
            to: source("global", "dim_avfallshåndtering")
            to_columns: ["`avfallshåndtering_pk`"]
```
3) Run the model 
`dbt build --select my_model`

### Expected behavior
dbt build --select my_model should build without failing, and the foreign key constraint should be applied to the model.

### Screenshots and log output
```
13:11:48  1 of 1 ERROR creating sql table model my_model ........... [ERROR in 2.22s]
13:11:49  
13:11:49  Finished running 1 table model in 0 hours 0 minutes and 4.88 seconds (4.88s).
13:11:49  
13:11:49  Completed with 1 error, 0 partial successes, and 0 warnings:
13:11:49  
13:11:49    Database Error in model my_model (models/my_model.sql)

  [INVALID_IDENTIFIER] The unquoted identifier avfallshåndtering_fk is invalid and must be back quoted as: `avfallshåndtering_fk`.
  Unquoted identifiers can only contain ASCII letters ('a' - 'z', 'A' - 'Z'), digits ('0' - '9'), and underbar ('_').
  Unquoted identifiers must also not start with a digit.
```

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.9.3
  - latest:    1.9.3 - Up to date!

Plugins:
  - spark:      1.9.2         - Up to date!
  - databricks: 1.10.0-alpha1 - Ahead of latest version!```
```

**The operating system you're using:**
`Ubuntu 24.04.02 LTS`

**The output of `python --version`:**
`Python 3.12.3`

### Additional context
