### ISSUE TITLE
constraints not shown in docs

### ISSUE THREAD

**Issue by frankivo** [databricks/dbt-databricks#970]
### Describe the bug
defined not_null, pk and fk in model yml. generated static docs.
docs do not show anything in the "constraints" column for said model.

tried both dbt-databricks and dbt-duckdb

### Steps To Reproduce
```  
constraints:
        - type: primary_key
          name: pk__fact_contract_hrm
          columns: [EmployeeContractKey]
        - type: not_null
          columns: [EmployeeContractKey]
        - type: foreign_key
          name: fk__fact_contract_hrm__employee
          columns: [EmployeeKey]
          to: ref("dim_employee_hrm")
          to_columns: [EmployeeKey]
```
dbt docs generate --static
dbt serve

### Expected behavior
expecting constraints in generated documentation.

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.9.3
  - latest:    1.9.3 - Up to date!

Plugins:
  - databricks: 1.9.7 - Up to date!
  - duckdb:     1.9.2 - Up to date!
  - spark:      1.9.0 - Update available!
```

**The operating system you're using:**

**The output of `python --version`:**
