### ISSUE TITLE
Unable to pass _tls_trusted_ca_file in the profile

### ISSUE THREAD

**Issue by sivadotblog** [databricks/dbt-databricks#986]
### Describe the bug
Typically, when we use databricks-sql-connector we can specify cert files using _tls_trusted_ca_file. However 

```
    connection = connect(
        server_hostname=host,
        http_path=http_path,
        access_token="pat",
        # # auth_type="databricks-oauth",
        # client_id=client_id,
        # client_secret=client_secret
        _tls_trusted_ca_file='C:\\Users\\user_id\\certs\\cacerts.pem',  # Use the certificate bundle directly
    )
```
However with dbt- databricks I have no way of passing it and so i get the following error

```'
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1006)'))': /sql/1.0/warehouses/9fb8c8*******61604b
17:01:53  Databricks adapter: Connection(session-id=Unknown) - Exception while trying to create connection: Error during request to server. Retry request would exceed Retry policy max retry duration of 900.0 seconds
```
### Steps To Reproduce

**profiles.yaml**
```
  outputs:
    local:
      type: databricks
      catalog: "{{ env_var('DATABRICKS_CATALOG') }}"
      schema: "{{ env_var('DATABRICKS_SCHEMA') }}"
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_SQL_HTTP_PATH') }}"
      auth_type: oauth
      client_id: "{{ env_var('OAUTH_CLIENT_ID') }}"
      client_secret: "{{ env_var('OAUTH_CLIENT_SECRET') }}"
      threads: 1
```
create a sample model and run 
```
dbt run  --target local
```

All the env variables such as REQUESTS_CA_BUNDLE, SSL_CERT_FILE, GRPC_DEFAULT_SSL_ROOTS_FILE_PATH (not relevant) are set.

If I use databricks.sql.connect, i can pass the cert fil and the connect is successful. With DBT I get the SSL error mentioned above 

### Expected behavior
I expect the model to complete successfully

### Screenshots and log output

```'
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1006)'))': /sql/1.0/warehouses/9fb8c8*******61604b
17:01:53  Databricks adapter: Connection(session-id=Unknown) - Exception while trying to create connection: Error during request to server. Retry request would exceed Retry policy max retry duration of 900.0 seconds
```

### System information
**The output of `dbt --version`:**
```
C:\Users\****\code\dataplatform-databricks-dbt\venv2\Lib\site-packages\pydantic\_internal\_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'validate_by_name'
  warnings.warn(message, UserWarning)
Core:
  - installed: 1.9.4

  The latest version of dbt-core could not be determined!
  Make sure that the following URL is accessible:
  https://pypi.org/pypi/dbt-core/json

Plugins:
  - databricks: 1.9.7 - Could not determine latest version
  - spark:      1.9.2 - Could not determine latest version


```

**The operating system you're using: Windows 11**

**The output of `python --version`: Python 3.11.7**

### Additional context
I was able to get past it by editing the sql/client.py in the virtual python environment . its a super dirty workaround

![Image](https://github.com/user-attachments/assets/e493c4f0-faf4-458a-934a-10c61face5b6)
